create table MAXUSER (
	userid INT,
	name VARCHAR(50),
	type VARCHAR(8)
);
insert into MAXUSER (userid, name, type) values (1, 'Eduardo Morrowe', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (2, 'Franny Sarfat', 'LABOR');
insert into MAXUSER (userid, name, type) values (3, 'Ray Boots', 'MANAGER');
insert into MAXUSER (userid, name, type) values (4, 'Basilio Wrintmore', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (5, 'Rene Size', 'LABOR');
insert into MAXUSER (userid, name, type) values (6, 'Fawne Cisec', 'MANAGER');
insert into MAXUSER (userid, name, type) values (7, 'Madel Pickaver', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (8, 'Spenser Newrick', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (9, 'Tamera Goodband', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (10, 'Winn L''Episcopio', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (11, 'Chastity Clavey', 'LABOR');
insert into MAXUSER (userid, name, type) values (12, 'Gianna Leverich', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (13, 'Christabella Bolam', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (14, 'Albertina Micheau', 'LABOR');
insert into MAXUSER (userid, name, type) values (15, 'Farica Chittim', 'MANAGER');
insert into MAXUSER (userid, name, type) values (16, 'Gawen Bolam', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (17, 'Cathryn Hickisson', 'LABOR');
insert into MAXUSER (userid, name, type) values (18, 'Lanette Youle', 'LABOR');
insert into MAXUSER (userid, name, type) values (19, 'Pincus Pietasch', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (20, 'Winnah Piddletown', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (21, 'Harlene McGairl', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (22, 'Hersh Casado', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (23, 'Ilysa Hellicar', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (24, 'Maurizio Ruste', 'LABOR');
insert into MAXUSER (userid, name, type) values (25, 'Malia Duprey', 'LABOR');
insert into MAXUSER (userid, name, type) values (26, 'Grover Atterley', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (27, 'Christoforo Crips', 'MANAGER');
insert into MAXUSER (userid, name, type) values (28, 'Mireille Ickov', 'LABOR');
insert into MAXUSER (userid, name, type) values (29, 'Geneva McCurley', 'MANAGER');
insert into MAXUSER (userid, name, type) values (30, 'Agosto Haylands', 'LABOR');
insert into MAXUSER (userid, name, type) values (31, 'Beckie Hainning', 'MANAGER');
insert into MAXUSER (userid, name, type) values (32, 'Rycca Dowden', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (33, 'Gerome Steere', 'MANAGER');
insert into MAXUSER (userid, name, type) values (34, 'Delinda Coste', 'MANAGER');
insert into MAXUSER (userid, name, type) values (35, 'Lucius Gwillyam', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (36, 'Claudetta Stearndale', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (37, 'Elia Frugier', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (38, 'Ddene Chiverstone', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (39, 'Meaghan Percifer', 'MANAGER');
insert into MAXUSER (userid, name, type) values (40, 'Marje Surridge', 'MANAGER');
insert into MAXUSER (userid, name, type) values (41, 'Orton Dilliway', 'MANAGER');
insert into MAXUSER (userid, name, type) values (42, 'Ralina Meekin', 'LABOR');
insert into MAXUSER (userid, name, type) values (43, 'Lionel Fadell', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (44, 'Fredrika Van Hault', 'MANAGER');
insert into MAXUSER (userid, name, type) values (45, 'Audra MacParland', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (46, 'Phil Ludgrove', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (47, 'Aida Feyer', 'LABOR');
insert into MAXUSER (userid, name, type) values (48, 'Mersey Goldby', 'MANAGER');
insert into MAXUSER (userid, name, type) values (49, 'Niven Pitkin', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (50, 'Jazmin Le Sarr', 'LABOR');
insert into MAXUSER (userid, name, type) values (51, 'Jenifer McComb', 'MANAGER');
insert into MAXUSER (userid, name, type) values (52, 'Elisabetta Ruffey', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (53, 'Jill Backshaw', 'MANAGER');
insert into MAXUSER (userid, name, type) values (54, 'Andrus Biggerstaff', 'LABOR');
insert into MAXUSER (userid, name, type) values (55, 'Nessi Gainsbury', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (56, 'Val Tuny', 'LABOR');
insert into MAXUSER (userid, name, type) values (57, 'Wileen Fairrie', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (58, 'Kristoffer Ailmer', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (59, 'Carie Henstridge', 'LABOR');
insert into MAXUSER (userid, name, type) values (60, 'Dehlia Sywell', 'MANAGER');
insert into MAXUSER (userid, name, type) values (61, 'Coleen Dagger', 'LABOR');
insert into MAXUSER (userid, name, type) values (62, 'Ernest Caulliere', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (63, 'Brig Kesterton', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (64, 'Vaughan Cecil', 'MANAGER');
insert into MAXUSER (userid, name, type) values (65, 'Hatti Vogl', 'MANAGER');
insert into MAXUSER (userid, name, type) values (66, 'Krishnah Broke', 'MANAGER');
insert into MAXUSER (userid, name, type) values (67, 'Evered Sappy', 'LABOR');
insert into MAXUSER (userid, name, type) values (68, 'Audrie Blaxall', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (69, 'Ethel Audley', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (70, 'Olenolin Roxby', 'LABOR');
insert into MAXUSER (userid, name, type) values (71, 'Merci Bolsteridge', 'MANAGER');
insert into MAXUSER (userid, name, type) values (72, 'Cal Owthwaite', 'MANAGER');
insert into MAXUSER (userid, name, type) values (73, 'Raphael Mytton', 'LABOR');
insert into MAXUSER (userid, name, type) values (74, 'Holden Noon', 'LABOR');
insert into MAXUSER (userid, name, type) values (75, 'Chrissie Beardwood', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (76, 'Fan Leggs', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (77, 'Bride Sandry', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (78, 'Padraic Babber', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (79, 'Almira Vaughn', 'LABOR');
insert into MAXUSER (userid, name, type) values (80, 'Chev Sadler', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (81, 'Meade McNern', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (82, 'Millard Giraudoux', 'MANAGER');
insert into MAXUSER (userid, name, type) values (83, 'Lyon Kitchingman', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (84, 'Alleen Munks', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (85, 'Tiena Saffer', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (86, 'Korney Ege', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (87, 'Gabriella Tassel', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (88, 'Butch Stillwell', 'LABOR');
insert into MAXUSER (userid, name, type) values (89, 'Orella Ickovits', 'LABOR');
insert into MAXUSER (userid, name, type) values (90, 'Finley Faloon', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (91, 'Juliette Ibbison', 'LABOR');
insert into MAXUSER (userid, name, type) values (92, 'Ofelia Jerome', 'MANAGER');
insert into MAXUSER (userid, name, type) values (93, 'Drud Petteford', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (94, 'Barn Rawlingson', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (95, 'Lindsey Ashard', 'MANAGER');
insert into MAXUSER (userid, name, type) values (96, 'Jenna Guildford', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (97, 'Marcella Lyosik', 'IT STAFF');
insert into MAXUSER (userid, name, type) values (98, 'Evelin Tavner', 'ENGINEER');
insert into MAXUSER (userid, name, type) values (99, 'Myrtia Vouls', 'LABOR');
insert into MAXUSER (userid, name, type) values (100, 'Darin Barbosa', 'IT STAFF');



create table LOGINTRACKING (
	userid VARCHAR(2),
	Attemptdate VARCHAR(50),
	attempttype VARCHAR(6)
);
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (1, '2022-05-25 09:54:13', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (3, '2022-03-29 08:50:19', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (7, '2023-01-02 11:33:41', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (8, '2022-05-11 22:32:46', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (8, '2022-08-24 16:46:54', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-06-13 15:56:42', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (19, '2022-11-13 17:46:29', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2022-03-09 06:20:42', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-02-25 04:58:39', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (22, '2022-09-24 17:03:30', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (16, '2022-09-06 01:29:16', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2022-12-06 06:56:50', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-11-28 11:49:38', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (2, '2022-05-15 23:38:52', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (7, '2022-10-24 23:53:02', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-06-14 01:33:14', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-02-10 06:12:59', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (3, '2022-01-29 05:03:25', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (7, '2022-05-22 09:01:17', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (2, '2022-09-26 00:35:13', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (1, '2022-02-15 09:18:39', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (6, '2022-06-07 19:34:59', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (8, '2022-04-18 11:52:22', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (2, '2022-01-14 13:48:34', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-01-24 01:40:46', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (3, '2022-04-09 10:35:20', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-11-03 04:20:00', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (22, '2022-06-07 17:21:51', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-07-23 12:49:15', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (3, '2022-08-04 21:55:56', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-04-08 22:56:09', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-07-29 04:36:25', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2022-08-12 06:39:09', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (8, '2022-10-14 00:05:07', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-09-03 11:14:16', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (6, '2022-03-21 10:43:54', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-05-01 04:33:14', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (6, '2022-10-20 16:42:12', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-05-16 22:02:31', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (16, '2022-08-22 23:57:09', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (1, '2022-05-27 06:53:04', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-11-06 16:05:27', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-08-18 08:40:41', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (7, '2022-03-31 18:22:50', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-10-18 10:22:19', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-08-18 14:55:25', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2022-11-09 15:19:10', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (2, '2022-04-09 01:30:34', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (6, '2022-05-13 10:55:42', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2022-11-25 21:16:39', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (7, '2022-06-06 07:46:24', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (12, '2022-04-17 14:11:29', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (12, '2022-02-28 06:31:52', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-10-04 18:49:09', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (7, '2022-07-21 07:05:02', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-11-04 15:38:24', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-11-29 21:48:36', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-10-29 06:04:36', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (19, '2022-02-17 16:47:10', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-05-16 08:38:06', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (22, '2022-11-15 16:59:42', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (1, '2022-04-14 02:16:48', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-11-28 03:32:01', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (16, '2022-09-01 12:57:43', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (1, '2022-12-14 09:33:24', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (2, '2022-03-27 13:53:54', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-03-25 08:08:52', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (8, '2023-01-02 15:00:17', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2022-11-09 12:18:55', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (22, '2022-08-16 18:40:26', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (7, '2022-08-27 16:06:53', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (8, '2022-03-09 07:18:28', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (3, '2022-07-25 10:07:58', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (2, '2022-12-15 13:14:54', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (1, '2022-08-21 14:19:32', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2023-01-04 03:05:04', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (19, '2022-01-26 05:36:36', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (2, '2022-01-11 00:14:32', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2022-09-04 06:39:48', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (7, '2022-03-17 21:33:13', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (16, '2022-07-25 20:43:47', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (2, '2022-06-08 17:39:58', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (19, '2022-08-18 16:48:25', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (35, '2022-11-11 08:19:13', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2022-02-18 20:09:27', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (19, '2022-01-21 10:58:00', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-12-07 18:04:41', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (19, '2022-02-07 09:14:15', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-04-03 06:36:27', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (1, '2022-02-20 19:48:37', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-04-15 06:53:32', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (1, '2022-10-06 13:39:33', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (4, '2022-11-05 02:20:20', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (8, '2022-11-28 09:35:49', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (3, '2022-12-09 08:43:14', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (3, '2022-08-28 20:00:43', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (6, '2022-07-13 22:37:59', 'LOGOUT');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-02-02 11:49:20', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (5, '2022-05-14 13:28:25', 'LOGIN');
insert into LOGINTRACKING (userid, Attemptdate, attempttype) values (11, '2022-05-29 15:00:16', 'LOGOUT');

